### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by jgreefmiso**
Develop is in a stable state, so lets get it into master before we mess with it again.

### CODE REVIEW

**Comment by Schwo0ps** [comment]
@jgreefmiso Did you tag a version?

**Comment by jgreefmiso** [comment]
I don't know what that means.

**Comment by Schwo0ps** [comment]
Since it's a ROS package, you need to run through a few commands to properly "release" a new version: https://github.com/MisoRobotics/miso-bash/blob/develop/bin/finalize-release

Also, we are following https://nvie.com/posts/a-successful-git-branching-model/ for git branches. The document is also mounted in the office on the southern wall. The main takeaway is to create a release branch with commits in it to bump the version, and to create a tag at master after merging (see https://github.com/MisoRobotics/miso-bash/blob/develop/bin/backmerge-release).

With catkin, there will basically be 2 commits created. "Update changelog" and "<version number>". See the last 2 commits in https://github.com/MisoRobotics/ml_weights/pull/39 for example.

Since this is the first time master is used (as I understand), it doesn't matter too much, but keep it in mind for future releases. Usually, we use the scripts to generate releases for every package in the workspace, so it doesn't always matter, but sometimes it will.

**Comment by Schwo0ps** [comment]
This document should hopefully have a lot of this explained, but let me know if it's missing: https://misorobotics.atlassian.net/wiki/spaces/~19189847/pages/262340712/Git+Workflow

**Pull request merged**
